name: Smoke

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Run local checkout action
        uses: ./
        with:
          repository: p6m7g8-actions/checkout
          fetch-depth: 1
